POST https://vehicles-backend-58d7.onrender.com/vehicles
Content-Type: application/json

{
    "placa": "ABC-1234",
    "chassi": "9BWZZZ377VT004251",
    "renavam": "12345678901",
    "modelo": "Gol",
    "marca": "Volkswagen",
    "ano": 2020
}

###
GET https://vehicles-backend-58d7.onrender.com/vehicles?search=placa
Content-Type: application/json

###
PUT https://vehicles-backend-58d7.onrender.com/vehicles/fd3fce77-d540-4c72-9098-0481360893e0
Content-Type: application/json

{
    "placa": "DEF-5678",
    "chassi": "8APZZZ123LT009876",
    "renavam": "98765432102",
    "modelo": "Onix",
    "marca": "Chevrolet",
    "ano": 2021
}

###
DELETE https://vehicles-backend-58d7.onrender.com/vehicles/fd3fce77-d540-4c72-9098-0481360893e0
